[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/templates/**"]

[[redirects]]
  from = "https://doc-scout.netlify.app/*"
  to = "https://doc-scout.jimut.in/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
